#!/bin/bash
#
#mysql paigaldamine
#
MYSQL=$(dpkg-query -W -f='${Status}' mysql 2>/dev/null | grep -c "ok installed")
#
if [ $MYSQL -eq 0 ]; then
	echo "paigalda mysql"
	apt-get install -y mysql-server;
#
elif [ $MYSQL -eq 1 ]; then
	echo "mysql on paigaldatud!"
	service php status
fi
